### ISSUE TITLE
Dev proxy might not be working

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#182]
It seems like the dev proxy is misconfigured (or my understanding of how it works is wrong).

From looking at the `dev.conf` in `modules/proxy`, the dashboard should be available at `http://localhost`, and the hub should be available at `http://localhost/api/hub/`. However I can't access the hub API endpoints at the URL nor the dashboard. I can only access them if I hit their direct exposed ports, i.e. `http://localhost:8080` for the hub and `http://localhost:3000` for the dashboard.

**Comment by bohendo** [comment]
The above assumes the `$hostname` is localhost(:80) but port 80 has been reserved so that the daicard can run alongside the hub in dev-mode. [The port used for the hub proxy in dev-mode is 3000](https://github.com/ConnextProject/indra/blob/master/ops/deploy.dev.sh#L117).

If I run `curl http://localhost:3000/api/hub/config` I get the output I expect.

**Comment by rhlsthrm** [comment]
Ah okay, makes sense!
