### ISSUE TITLE
Handle in flight deposits

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#237]
We need to check when deposits are being sent to chain and block further deposits (protocol level error). Right now, someone can request a deposit while another deposit is already in progress, which throws a poorly handled error.

In order for this to be properly fixed, we need some additional data from the CF events, and specifically for them to conform to the `NodeMessage` type.

Alternatively, if there's a way to alleviate this requirement (e.g could be a pain that collateralizing deposits are blocking ops), that would be even better.

**Comment by LayneHaber** [comment]
Should also update the collateral algorithm to check for any in flight deposits

**Comment by ArjunBhuptani** [comment]
@cf19drofxots @snario FYI.

We can make a follow up issue in your repo re: new events too

**Comment by rhlsthrm** [comment]
Currently blocked by this issue: https://github.com/counterfactual/monorepo/issues/2304

**Comment by cf19drofxots** [comment]
I'm tackling most (if not all) of these deposit related issues today.

**Comment by cf19drofxots** [comment]
> We need to check when deposits are being sent to chain and block further deposits (protocol level error). Right now, someone can request a deposit while another deposit is already in progress, which throws a poorly handled error.

So after looking at this and implementing what I thought was the fix, it turns out due to the current queueing implementation, it doesn't seem possible that multiple deposits can take place simultaneously since there's a lock on any channel operations until an in-progress deposit has finished.

The subsequent deposit requests simply get added to a queue dedicated specifically for the relevant channel.

@LayneHaber can you paste the logs you're seeing around this issue? The problem is _probably_ something else.

**Comment by rhlsthrm** [comment]
@cf19drofxots the issue is not the way you describe. This is an app-level issue on our side. We have clients "request collateral" from the hub. We use an algorithm to determine how much the hub deposits as collateral. If the deposit is in progress (i.e. "in flight"), and the client requests collateral again, then we will not know that we have already started sending collateral, then we will send more collateral.

This is why we need the Deposit Confirmed event to throw, which seems to not be happening for some reason.

**Comment by cf19drofxots** [comment]
@rhlsthrm thanks for explaining.

Can you apply this patch locally and see if you observe the event being emitted? https://github.com/counterfactual/monorepo/pull/2321/files

**Comment by cf19drofxots** [comment]
@rhlsthrm @LayneHaber did that patch do anything?

**Comment by rhlsthrm** [comment]
@cf19drofxots had to switch gears to get back to testing the concurrency issue. I'll jump back onto this after I finish that, hopefully today.

**Comment by hthillman** [comment]
@rhlsthrm can you provide an update here?
