### ISSUE TITLE
[node] Directly implement lock and unlock calls

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#326]
Allow for multi-hub use case.

**Comment by kthomas** [comment]
We can use the `_lock()` method (see https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L328) on the `Redlock` instance and pass a `value` as the second argument before our `ttl`. The client can generate that value using something along the lines of `crypto.randomBytes(16).toString('hex');`.

When we are ready to release the lock, send the `value` generated above in the unlock message. We will need to manually invoke redis instead of calling `lock.unlock()` since we won't have a handle on the lock instance. Storing the lock in memory reintroduces race conditions on the lock itself (i.e., this races: https://github.com/ConnextProject/indra/pull/312/files#diff-19da9763be45521b36752267c8208a0bR44 and also introduces security issues, even when requests are authorized). The manual invocation will look similar to this: https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L233-L244

**Comment by rhlsthrm** [comment]
Fixed by this commit: https://github.com/ConnextProject/indra/pull/312/commits/aa0935aa4ead0077dd97f22ec362b6579d1c8233
