### ISSUE TITLE
[contracts, node, client] Make async transfer app use recipient at contract layer

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#398]
Right now, anyone can dispute a linked payment with the pre-image. This is desirable for normal links, but we should make a new linked payment with recipient app to make the logic work in the contract layer.

**Comment by ArjunBhuptani** [comment]
Thinking more about this:

There's never really a case where any third party could dispute without having a signed commitment from a channel participant. Additionally, we're encrypting the preimage with the recipient's key, which protects against the node from doing this.

To the contract logic, having the recipient be defined in the app state is somewhat meaningless:
1. For the sender's app, the recipient isn't a channel participant so the app couldn't possibly do anything with that info.
2. For the receiver's app, the recipient is a channel participant, but in that case they're already signing using their key in order to take action in the channel. Having their address be a part of the hash is then pretty meaningless.

Closing this for now
