### ISSUE TITLE
Business Logic for Thread Update

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#41]
The following changes still need to be made in order to allow the hub to handle threads

- [ ] Collateralization algorithm needs to be tweaked (@rhlsthrm what needs to happen here?)
- [ ] Add a tunable fee on each payment. Thread updates should be rejected if they don't include fee.

**Comment by ArjunBhuptani** [comment]
I'd like to do a sanity check here @rhlsthrm. Still have the following questions:

1. How will collateralization need to be amended?
2. Hubs don't take any action on thread updates other than to just save them to DB correct? Are we doing any verification currently? 
(Technically, thread updates should not be able to be censored by hub, it's okay if we do this for now but long term we need to find a better way to deal with fees. Otherwise, sender can just give state directly to receiver bypassing the hub - how would they then collect fees?)
3. Do we need to include token withdrawals here or can they be part of a larger refactor? Allowing for token withdrawals is the same _core_ issue as allowing for users to pay gas for withdrawals i.e. we would need to create generalized userAuthUpdate handlers with tunable logic that is injected

**Comment by rhlsthrm** [comment]
> How will collateralization need to be amended?
Collateralization shouldn't need to be amended at all, the collateralization for instant custodial payments should be sufficient to get threads working (since it was designed for threads to begin with). There is a caveat that we can only pay with tokens into threads, but we can abstract that out with in-channel swaps.

> Hubs don't take any action on thread updates other than to just save them to DB correct? Are we doing any verification currently? (Technically, thread updates should not be able to be censored by hub, it's okay if we do this for now but long term we need to find a better way to deal with fees. Otherwise, sender can just give state directly to receiver bypassing the hub - how would they then collect fees?)
Right now we just verify the signer. We can also set up the hub to use the validation library to make sure the states are generated correctly. However as you said, we shouldn't worry about too much validation here.

>Do we need to include token withdrawals here or can they be part of a larger refactor? Allowing for token withdrawals is the same core issue as allowing for users to pay gas for withdrawals i.e. we would need to create generalized userAuthUpdate handlers with tunable logic that is injected
It seems to me like this is a completely different task.

**Comment by rhlsthrm** [comment]
The main task seems to be here to figure out how to build in the fee.
