### ISSUE TITLE
[cf-core] Add bytecode to channel store objects

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#553]
- [ ] Update NetworkContext object to accept bytecode in addition to contract addresses (alternatively, just make a separate parameter for creating CF Core object).
- [ ] Store bytecode in channel store as part of creation
- [ ] Use stored bytecode for multisig address calculations

**Comment by bohendo** [comment]
Copy/paste of a relevant discord braindump:

My initial thought was to keep track of a set of all proxy bytecodes we've everused so if someone wants to withdraw from an old one, we have the bytecode necessary to deploy to generate a contract at their channel's multisig address.. this will not work
When deploying the proxy, we don't actually touch it's bytecode, we call proxyFactory.createProxyWithNonce(multisigAddress, initOwnersData, nonce)
For some reason I thought we had to provide the bytecode we're deploying at deploy time but nope. That bytecode is decided on at build time.
Critical discovery: The Proxy bytecode we're deploying is embedded inside the proxyFactory's bytecode.. and when we call createProxyWithNonce the factory pulls the Proxy's creation-bytecode out of it's own bytecode and deploys that
reference: https://solidity.readthedocs.io/en/v0.5.11/units-and-global-variables.html#type-information
Now I understand why these bytecode problems have been such big problems
BUT I think there's a fairly simple solution
Instead of an array of proxyBytecodes, we maintain an array of all the historical proxyFactory addresses that we've ever used. The proxyFactory has a proxyCreationCode method that returns the proxy bytecode so we have a direct way to go proxyFactoryAddress -> proxyBytecode while calculating multisig addresses
This means, instead of the proxyBytecode in the state, we should be including the proxyFactoryAddress
And we should pretty much never touch the bytecode imported from the contract build artifacts

Plan moving forward w the 553 branch:
 - Replace updates to cf-core's StateChannel that adds proxyBytecode to the state with the addition of proxyFactoryAddress
 - Replace every instance of Proxy.evm.bytecode.object and replace it with something like await proxyFactory.proxyCreationCode()

But the changes aren't really that much different that what we've done so far. We can pretty much look at the diff & change each of our changes to use the bytecode getter instead of importing from build artifacts
