### ISSUE TITLE
Daicard seems to recollateralize multiple times when it's doing the first time swap after deposit

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#571]
**Describe the bug**
Seeing multiple collateralization logs. See attached screenshot.

**To Reproduce**
1. Deposit in fresh Daicard channel
2. Watch logs

**Expected behavior**
Only collateralize once.

**Screenshots**
<img width="351" alt="image" src="https://user-images.githubusercontent.com/11512787/69220600-b0973480-0b75-11ea-977d-c44ace2fba6f.png">

**Comment by LayneHaber** [comment]
Do we know that it's actually trying to collateralize? These logs are likely coming from the daicard autoswap fn

**Comment by ArjunBhuptani** [comment]
Any updates on this?

**Comment by LayneHaber** [comment]
I don't think it should be a problem if the client requests collateral multiple times, and the collateralization should be resilient enough to handle multiple requests. 

Did find an issue where a promise in the transfer function was auto-resolving if collateral was in flight rather than once the deposit was confirmed, but still shouldn't be a major issue. Will leave this open until that fix is in (in branch #568 cc @rhlsthrm)

**Comment by rhlsthrm** [comment]
> I don't think it should be a problem if the client requests collateral multiple times, and the collateralization should be resilient enough to handle multiple requests.

It's not that the client is requesting multiple times, what I observed is that the collateralization actually happened multiple times, doubling the amount of collateral that went into the channel.

**Comment by LayneHaber** [comment]
Is it still happening? I can try to repro today.

**Comment by ArjunBhuptani** [comment]
Remove explicit collateralization (it should happen automatically in client)

**Comment by LayneHaber** [comment]
Update: still happening. Fixed in #718
