### ISSUE TITLE
[cf-core] Tracker: Revisit virtual protocols

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#600]
From @LayneHaber's comments in Discord:
> the idea is the only time it’s okay to use a calculated multisig is when the channel is for all three people, or the end users, in any virtual agreement (so the virtual case in propose, install virtual, and uninstall virtual). Otherwise it should be pulled from the store because it involves the intermediary
> I’m pretty sure that was accounted for in your install virtual stuff with how the static fn was being used, but I think that may not be the case for uninstall
> 100% possible it was an existing issue (that I made)

Low priority right now because we aren't using virtual installs, but will escalate if we have a requirement.

**Comment by ArjunBhuptani** [comment]
Going to make this the master issue for all virtual protocols, closing the other ones.

**Comment by LayneHaber** [comment]
IIRC there were some other questions about the virtual install protocol, specifically there's no chance to `reject` an install if you're an intermediary since the `propose` is between the app participants exclusively.

This isn't so much a bug as it is a design caveat, IMO it seems reasonable for an intermediary to specifically *not* install proposed apps as well

**Comment by ArjunBhuptani** [comment]
For now, we've deleted virtual protocols entirely from cf-core. Closing.
