### ISSUE TITLE
URLs for Maintained/staging Hubs

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#95]
Prod rinkeby, mainnet, and staging for both should have different URLs.

There should be an easy way to deploy to these different environments.

The staging URLs can be "*.connext.network" and the prod ones can be under "daicard.io" or "rinkeby.daicard.io"

The wallet should be able to switch between these (the network handler should be setup for this already), depending on the node env (staging, prod, etc) or however you decide is easiest

**Comment by bohendo** [comment]
I vote we have a single prod UI: daicard.io and a single staging ui: card.connext.network.

In the settings, the prod or staging UIs can switch between hubs that are at mainnet.hub.connext.network (maybe just hub.connext.network) or rinkeby.hub.connext.network or localhost:8080. We can also have an additional staging hub at staging.hub.connext.network for our own debugging purposes.

**Comment by bohendo** [comment]
Battle plan:
 - `daicard.io`: Deploy a new, slightly beefier server & use this in production.
 - `hub.connext.network`: Deploy a new server & configure it in preparation for mainnet launch
 - `card.connext.network`: Use the old, wimpy daicard server & use it as our card's staging server.
 - `rinkeby.hub.connext.network`: We can use our old hub server for this & use it for both staging and the "rinkeby" mode of the live daicard.io

We'll try to set all of this up on a call tomorrow so that everyon'e up to date on how the devops stuff works in prod.

**Comment by LayneHaber** [comment]
Need to be moved over to appropriate AWS ownership, @rhlsthrm think you're the only one who can get that done

**Comment by rhlsthrm** [comment]
I think this is all done now, @bohendo is there anything else I need to do here?
